apiVersion: apps/v1
kind: Deployment
metadata:
  name: webecho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webecho
  template:
    metadata:
      labels:
        app: webecho
    spec:
      containers:
      - name: webecho
        image: davidwashere/webecho:latest

