name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string


jobs:
  binaries:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"
      - name: build
        run: |
          go run ./build

          ls -lR .
          cd bin/release
          files=$(go run ./build --list)
          echo "files: $files"
          gh release create ${{ inputs.tag }} $files


  # docker:
  #   runs-on: ubuntu-latest
  #   needs: binaries
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: davidwashere/webecho:latest, davidwashere/webecho:${{ inputs.tag }}
